---
# Project information
site_name: PA De Carvalho CV
site_url: https://pa-decarvalho.github.io/pa-decarvalho/
site_description: PA De Carvalho - Curriculum Vitae

# Theme
theme:
  name: curriculum-vitae
  mkcv_theme: nes
  main_title: Philippe-André De Carvalho
  firstname: Philippe-André
  lastname: De Carvalho
  mail: philippe.andre.decarvalho@gmail.com
  location: France
  profile_picture: https://avatars.githubusercontent.com/pa-decarvalho
  personnal_links:
    github: https://github.com/pa-decarvalho
    gitlab: https://gitlab.com/philippe.andre.decarvalho
  experiences:
    - title: Education nationale
      description: DevOps Engineer
      start_date: 2025-09-01
    - title: Neo-Soft
      description: DevOps Engineer
      start_date: 2019-10-01
      end_date: 2025-08-29
    - title: Arondor
      description: Java Developer
      start_date: 2018-04-01
      end_date: 2019-10-01
  educations:
    - title: EPITECH
      description: Computer science
      start_date: 2014-09-01
      end_date: 2017-07-31
    - title: Advanced Technician's Certificate
      description: Automatic System Design and Production
      start_date: 2012-09-01
      end_date: 2014-07-31
  skills:
    - Python
    - Ansible
    - Molecule
    - Docker
    - Gitlab CI
    - Terraform
    - MkDocs
  hobbies:
    - Video games
    - Open source projects
    - Sports
  certifications:
    - name: Professional Scrum Master™ I
      link: https://www.credly.com/badges/4693b141-edc7-416a-9813-7f3b5c68564f

# Plugins
plugins:
  - search
